title:             Gabriel's Blog
email:             gabrielwfeng@gmail.com
description:
author:            Gabriel Feng
baseurl:           "gabrielwf.me"
url:               "gabrielwf.me"

# Social Profiles
twitter_username:  gabriel_feng
github_username:   gabrielvon
linkedin_username:   gabriel feng
instagram_username:   gabrielfeng
# facebook_username: StartBootstrap

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
