title:             Gabriel's Blog
email:             gabrielwfeng@gmail.com
description:
author:            Gabriel Feng
baseurl:           "/"
url:               "/"

# Social Profiles
twitter_username:  gabriel_feng
github_username:   gabrielvon
instagram_username:   gabrielfeng
linkedin_username:   gabrielfeng
# facebook_username: StartBootstrap

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Google Analytics
ga_track_id: 'UA-74828864-4'            # Format: UA-xxxxxx-xx
ga_domain: gabrielwf.me